#pragma once

// Classic2USB: all retro protocol inputs.
#define ENABLE_INPUT_DREAMCAST
#define ENABLE_INPUT_N64
#define ENABLE_INPUT_GAMECUBE
#define ENABLE_INPUT_SATURN
#define ENABLE_INPUT_MEGADRIVE
#define ENABLE_INPUT_PSX
#define ENABLE_INPUT_PSX_JOG
#define ENABLE_INPUT_NES
#define ENABLE_INPUT_SNES
#define ENABLE_INPUT_VBOY
#define ENABLE_INPUT_PCE
#define ENABLE_INPUT_WII
#define ENABLE_INPUT_NEOGEO
#define ENABLE_INPUT_3DO
#define ENABLE_INPUT_JAGUAR
#define ENABLE_INPUT_DRIVING
#define ENABLE_INPUT_SMS
#define ENABLE_INPUT_JPC

#ifndef CLASSIC2USB_DISABLE_INPUT_AUTODETECT
  #define ENABLE_INPUT_AUTODETECT
#endif

#if !defined(DISABLE_SERIAL_MEMCARD_API)
  #define ADAPT_FEATURE_SERIAL_MEMCARD_API 1
#endif

#if !defined(DISABLE_TTY2OLED_SERIAL)
  #define ENABLE_TTY2OLED_SERIAL 1
#endif

#if defined(ENABLE_INPUT_AUTODETECT) && !defined(AUTODETECT_ENABLE_PASSIVE_ASSIST)
  #define AUTODETECT_ENABLE_PASSIVE_ASSIST 1
#endif

#define ENABLE_OUTPUT_USB_MODES 1

#ifndef ENABLE_EXPERIMENTAL_XINPUT2P_OUTPUT
  #define ENABLE_EXPERIMENTAL_XINPUT2P_OUTPUT 1
#endif
