#pragma once

#include <stdint.h>

extern uint8_t snes_debug_tap0;
extern uint8_t snes_debug_tap1;
extern bool snes_debug_mtap_enabled0;
extern bool snes_debug_mtap_enabled1;
extern bool snes_debug_fourscore0;
extern bool snes_debug_fourscore1;
extern uint8_t snes_port0_controller_count;
extern uint8_t snes_port1_controller_count;
extern uint8_t snes_debug_dtype0;
extern uint8_t snes_debug_dtype1;
extern uint8_t snes_debug_stable_dtype0;
extern uint8_t snes_debug_stable_dtype1;
extern uint8_t snes_debug_candidate_dtype0;
extern uint8_t snes_debug_candidate_dtype1;
extern uint8_t snes_debug_candidate_count0;
extern uint8_t snes_debug_candidate_count1;
extern uint16_t snes_debug_glitch_frames0;
extern uint16_t snes_debug_glitch_frames1;
extern uint8_t snes_debug_id0;
extern uint8_t snes_debug_id1;
extern uint16_t snes_debug_raw_digital0;
extern uint16_t snes_debug_raw_digital1;
extern uint16_t snes_debug_filtered_digital0;
extern uint16_t snes_debug_filtered_digital1;
extern uint16_t snes_debug_extended0;
extern uint16_t snes_debug_extended1;
extern uint32_t snes_debug_filter_drop0;
extern uint32_t snes_debug_filter_drop1;
extern uint32_t snes_debug_invalid_frame0;
extern uint32_t snes_debug_invalid_frame1;
extern uint32_t snes_debug_invalid_id0;
extern uint32_t snes_debug_invalid_id1;
extern uint32_t snes_debug_all_pressed0;
extern uint32_t snes_debug_all_pressed1;
extern bool snes_debug_reset_pending;
extern uint16_t snes_debug_mouse_ext;
extern int8_t snes_debug_mouse_x;
extern int8_t snes_debug_mouse_y;
extern int8_t snes_debug_mouse_x_min;
extern int8_t snes_debug_mouse_x_max;
extern int8_t snes_debug_mouse_y_min;
extern int8_t snes_debug_mouse_y_max;
extern uint16_t snes_debug_mouse_x_min_ext;
extern uint16_t snes_debug_mouse_x_max_ext;
extern uint16_t snes_debug_mouse_y_min_ext;
extern uint16_t snes_debug_mouse_y_max_ext;
extern uint8_t snes_debug_mouse_buttons;
extern uint8_t snes_debug_extend_count;
extern bool snes_rumbletech_detected0;
extern bool snes_rumbletech_detected1;
extern bool snes_debug_safe_poll0;
extern bool snes_debug_safe_poll1;
extern uint8_t snes_rumble_debug_data0;
extern uint8_t snes_rumble_debug_data1;
extern uint32_t snes_rumble_debug_tx0;
extern uint32_t snes_rumble_debug_tx1;

void setSnesPadDebugRaw(uint8_t index, uint8_t id, uint16_t digital, uint16_t extended);
void setSnesPadDebugFiltered(uint8_t index, uint16_t digital);
void noteSnesPadFilterDrop(uint8_t index);
void noteSnesPadInvalidFrame(uint8_t index);
void noteSnesPadInvalidId(uint8_t index);
void noteSnesPadAllPressed(uint8_t index);
void resetSnesPadDebugCounters();
void resetSnesMouseDebugRange();
