#include "../product_config.h"

#include "menu_pad_layouts_internal.h"

namespace menu_pad_layouts_internal {

const PadButton padLayoutWii[] = {
  { GPAD_L2, 0, 0 * 6, PAD_SHOULDER_ON, PAD_SHOULDER_OFF },
  { GPAD_L2, 0, 4 * 6, PAD_FACE_ON, PAD_FACE_OFF },
  { GPAD_R2, 0, 6 * 6, PAD_FACE_ON, PAD_FACE_OFF },
  { GPAD_R2, 0, 10 * 6, PAD_SHOULDER_ON, PAD_SHOULDER_OFF },
  { GPAD_UP, 1, 1 * 6, PAD_UP_ON, PAD_UP_OFF },
  { GPAD_DOWN, 3, 1 * 6, PAD_DOWN_ON, PAD_DOWN_OFF },
  { GPAD_LEFT, 2, 0, PAD_LEFT_ON, PAD_LEFT_OFF },
  { GPAD_RIGHT, 2, 2 * 6, PAD_RIGHT_ON, PAD_RIGHT_OFF },
  { GPAD_SELECT, 2, 4 * 6, PAD_FACE_ON, PAD_FACE_OFF },
  { GPAD_HOME, 2, 5 * 6, PAD_FACE_ON, PAD_FACE_OFF },
  { GPAD_START, 2, 6 * 6, PAD_FACE_ON, PAD_FACE_OFF },
  { GPAD_X, 1, 9 * 6, PAD_FACE_ON, PAD_FACE_OFF },
  { GPAD_Y, 2, 8 * 6, PAD_FACE_ON, PAD_FACE_OFF },
  { GPAD_A, 2, 10 * 6, PAD_FACE_ON, PAD_FACE_OFF },
  { GPAD_B, 3, 9 * 6, PAD_FACE_ON, PAD_FACE_OFF },
};
const uint8_t PAD_LAYOUT_WII_COUNT = sizeof(padLayoutWii) / sizeof(PadButton);

const PadButton padLayoutUsbModern[] = {
  { GPAD_L2, 0, 0 * 6, PAD_SHOULDER_ON, PAD_SHOULDER_OFF },
  { GPAD_L1, 0, 3 * 6, PAD_SHOULDER_ON, PAD_SHOULDER_OFF },
  { GPAD_R1, 0, 6 * 6, PAD_SHOULDER_ON, PAD_SHOULDER_OFF },
  { GPAD_R2, 0, 9 * 6, PAD_SHOULDER_ON, PAD_SHOULDER_OFF },
  { GPAD_UP, 1, 1 * 6, PAD_UP_ON, PAD_UP_OFF },
  { GPAD_DOWN, 3, 1 * 6, PAD_DOWN_ON, PAD_DOWN_OFF },
  { GPAD_LEFT, 2, 0, PAD_LEFT_ON, PAD_LEFT_OFF },
  { GPAD_RIGHT, 2, 2 * 6, PAD_RIGHT_ON, PAD_RIGHT_OFF },
  { GPAD_SELECT, 1, 3 * 6, PAD_RECT_ON, PAD_RECT_OFF },
  { GPAD_HOME, 1, (4 * 6) + 1, PAD_WIDE_CIRCLE_LEFT_ON, PAD_WIDE_CIRCLE_LEFT_OFF },
  { GPAD_START, 1, 6 * 6, PAD_RECT_ON, PAD_RECT_OFF },
  { GPAD_L3, 3, 3 * 6, PAD_FACE_ON, PAD_FACE_OFF },
  { GPAD_R3, 3, 6 * 6, PAD_FACE_ON, PAD_FACE_OFF },
  { GPAD_Y, 1, 8 * 6, PAD_FACE_ON, PAD_FACE_OFF },
  { GPAD_X, 2, 7 * 6, PAD_FACE_ON, PAD_FACE_OFF },
  { GPAD_B, 2, 9 * 6, PAD_FACE_ON, PAD_FACE_OFF },
  { GPAD_A, 3, 8 * 6, PAD_FACE_ON, PAD_FACE_OFF },
};
const uint8_t PAD_LAYOUT_USB_MODERN_COUNT =
    sizeof(padLayoutUsbModern) / sizeof(PadButton);

const PadButton padLayoutUsbSwitch[] = {
  { GPAD_L2, 0, 0 * 6, PAD_SHOULDER_ON, PAD_SHOULDER_OFF },
  { GPAD_L1, 0, 2 * 6, PAD_SHOULDER_ON, PAD_SHOULDER_OFF },
  { GPAD_R1, 0, 7 * 6, PAD_SHOULDER_ON, PAD_SHOULDER_OFF },
  { GPAD_R2, 0, 9 * 6, PAD_SHOULDER_ON, PAD_SHOULDER_OFF },
  { GPAD_UP, 1, 1 * 6, PAD_UP_ON, PAD_UP_OFF },
  { GPAD_DOWN, 3, 1 * 6, PAD_DOWN_ON, PAD_DOWN_OFF },
  { GPAD_LEFT, 2, 0, PAD_LEFT_ON, PAD_LEFT_OFF },
  { GPAD_RIGHT, 2, 2 * 6, PAD_RIGHT_ON, PAD_RIGHT_OFF },
  { GPAD_EXTRA0, 1, 4 * 6, PAD_RECT_ON, PAD_RECT_OFF },
  { GPAD_SELECT, 2, 4 * 6, PAD_RECT_ON, PAD_RECT_OFF },
  { GPAD_HOME, 2, 5 * 6, PAD_RECT_ON, PAD_RECT_OFF },
  { GPAD_START, 2, 6 * 6, PAD_RECT_ON, PAD_RECT_OFF },
  { GPAD_L3, 3, 3 * 6, PAD_FACE_ON, PAD_FACE_OFF },
  { GPAD_R3, 3, 6 * 6, PAD_FACE_ON, PAD_FACE_OFF },
  { GPAD_X, 1, 9 * 6, PAD_FACE_ON, PAD_FACE_OFF },
  { GPAD_Y, 2, 8 * 6, PAD_FACE_ON, PAD_FACE_OFF },
  { GPAD_A, 2, 10 * 6, PAD_FACE_ON, PAD_FACE_OFF },
  { GPAD_B, 3, 9 * 6, PAD_FACE_ON, PAD_FACE_OFF },
};
const uint8_t PAD_LAYOUT_USB_SWITCH_COUNT =
    sizeof(padLayoutUsbSwitch) / sizeof(PadButton);

const PadButton padLayoutSnes[] = {
  { GPAD_L1, 0, 1 * 6, PAD_SHOULDER_ON, PAD_SHOULDER_OFF },
  { GPAD_R1, 0, 8 * 6, PAD_SHOULDER_ON, PAD_SHOULDER_OFF },
  { GPAD_UP, 1, 1 * 6, PAD_UP_ON, PAD_UP_OFF },
  { GPAD_DOWN, 3, 1 * 6, PAD_DOWN_ON, PAD_DOWN_OFF },
  { GPAD_LEFT, 2, 0, PAD_LEFT_ON, PAD_LEFT_OFF },
  { GPAD_RIGHT, 2, 2 * 6, PAD_RIGHT_ON, PAD_RIGHT_OFF },
  { GPAD_SELECT, 2, 4 * 6, PAD_DASH_ON, PAD_DASH_OFF },
  { GPAD_START, 2, 5 * 6, PAD_DASH_ON, PAD_DASH_OFF },
  { GPAD_X, 1, 8 * 6, PAD_FACE_ON, PAD_FACE_OFF },
  { GPAD_Y, 2, 7 * 6, PAD_FACE_ON, PAD_FACE_OFF },
  { GPAD_A, 2, 9 * 6, PAD_FACE_ON, PAD_FACE_OFF },
  { GPAD_B, 3, 8 * 6, PAD_FACE_ON, PAD_FACE_OFF },
};
const uint8_t PAD_LAYOUT_SNES_COUNT = sizeof(padLayoutSnes) / sizeof(PadButton);

#ifdef ENABLE_INPUT_VBOY
const PadButton padLayoutVBoy[] = {
  { GPAD_L1, 0, 1 * 6, PAD_SHOULDER_ON, PAD_SHOULDER_OFF },
  { GPAD_R1, 0, 8 * 6, PAD_SHOULDER_ON, PAD_SHOULDER_OFF },
  { GPAD_UP, 1, 1 * 6, PAD_UP_ON, PAD_UP_OFF },
  { GPAD_DOWN, 3, 1 * 6, PAD_DOWN_ON, PAD_DOWN_OFF },
  { GPAD_LEFT, 2, 0, PAD_LEFT_ON, PAD_LEFT_OFF },
  { GPAD_RIGHT, 2, 2 * 6, PAD_RIGHT_ON, PAD_RIGHT_OFF },
  { GPAD_B, 3, (5 * 6) + 2, PAD_FACE_ON, PAD_FACE_OFF },
  { GPAD_A, 3, (6 * 6) + 2, PAD_FACE_ON, PAD_FACE_OFF },
  { GPAD_SELECT, 3, (3 * 6) - 2, PAD_FACE_ON, PAD_FACE_OFF },
  { GPAD_START, 3, (4 * 6) - 2, PAD_FACE_ON, PAD_FACE_OFF },
  { GPAD_X, 1, 8 * 6, PAD_UP_ON, PAD_UP_OFF },
  { GPAD_L2, 3, 8 * 6, PAD_DOWN_ON, PAD_DOWN_OFF },
  { GPAD_Y, 2, 7 * 6, PAD_LEFT_ON, PAD_LEFT_OFF },
  { GPAD_R2, 2, 9 * 6, PAD_RIGHT_ON, PAD_RIGHT_OFF },
};
const uint8_t PAD_LAYOUT_VBOY_COUNT = sizeof(padLayoutVBoy) / sizeof(PadButton);
#endif

const PadButton padLayoutN64[] = {
  { GPAD_L1, 0, 3 * 6, PAD_SHOULDER_ON, PAD_SHOULDER_OFF },
  { GPAD_R1, 0, 6 * 6, PAD_SHOULDER_ON, PAD_SHOULDER_OFF },
  { GPAD_UP, 0, 1 * 6, PAD_UP_ON, PAD_UP_OFF },
  { GPAD_DOWN, 2, 1 * 6, PAD_DOWN_ON, PAD_DOWN_OFF },
  { GPAD_LEFT, 1, 0, PAD_LEFT_ON, PAD_LEFT_OFF },
  { GPAD_RIGHT, 1, 2 * 6, PAD_RIGHT_ON, PAD_RIGHT_OFF },
  { GPAD_START, 2, 4 * 6, PAD_FACE_ON, PAD_FACE_OFF },
  { GPAD_L2, 3, 4 * 6, PAD_SHOULDER_ON, PAD_SHOULDER_OFF },
  { GPAD_B, 2, 6 * 6 - 2, PAD_FACE_ON, PAD_FACE_OFF },
  { GPAD_A, 3, 7 * 6 - 2, PAD_FACE_ON, PAD_FACE_OFF },
  { GPAD_X, 0, 8 * 6, PAD_FACE_ON, PAD_FACE_OFF },
  { GPAD_R2, 2, 8 * 6, PAD_FACE_ON, PAD_FACE_OFF },
  { GPAD_Y, 1, 7 * 6, PAD_FACE_ON, PAD_FACE_OFF },
  { GPAD_SELECT, 1, 9 * 6, PAD_FACE_ON, PAD_FACE_OFF },
};
const uint8_t PAD_LAYOUT_N64_COUNT = sizeof(padLayoutN64) / sizeof(PadButton);

const PadButton padLayoutGC[] = {
  { GPAD_L2, 0, 1 * 6, PAD_SHOULDER_ON, PAD_SHOULDER_OFF },
  { GPAD_R2, 0, 7 * 6, PAD_SHOULDER_ON, PAD_SHOULDER_OFF },
  { GPAD_SELECT, 1, 6 * 6, PAD_RECT_ON, PAD_RECT_OFF },
  { GPAD_UP, 1, 1 * 6, PAD_UP_ON, PAD_UP_OFF },
  { GPAD_DOWN, 3, 1 * 6, PAD_DOWN_ON, PAD_DOWN_OFF },
  { GPAD_LEFT, 2, 0, PAD_LEFT_ON, PAD_LEFT_OFF },
  { GPAD_RIGHT, 2, 2 * 6, PAD_RIGHT_ON, PAD_RIGHT_OFF },
  { GPAD_START, 2, 4 * 6, PAD_FACE_ON, PAD_FACE_OFF },
  { GPAD_Y, 2, 8 * 6, PAD_FACE_ON, PAD_FACE_OFF },
  { GPAD_B, 3, 7 * 6, PAD_FACE_ON, PAD_FACE_OFF },
  { GPAD_A, 3, 8 * 6, PAD_FACE_ON, PAD_FACE_OFF },
  { GPAD_X, 3, 9 * 6, PAD_FACE_ON, PAD_FACE_OFF },
};
const uint8_t PAD_LAYOUT_GC_COUNT = sizeof(padLayoutGC) / sizeof(PadButton);

}  // namespace menu_pad_layouts_internal
