#include "menu_catalog.h"

const menu_line_t menu_items[] = {
  { menu_item_input_mode, "In" },
  { menu_item_output_mode, "Out" },
  { menu_item_win_output, "Win Mode" },
  { menu_item_psx_periph, "PSX Periph" },
  { menu_item_nso_special, "NSO Mode" },
  { menu_item_analog_deadzone, "Deadzone" },
  { menu_item_analog_test, "Analog Test" },
  { menu_item_dpad_as_buttons, "DPad Mode" },
  { menu_item_socd, "SOCD" },
  { menu_item_display_contrast, "Contrast" },
  { menu_item_home_screen, "Home Screen" },
  { menu_item_home_button_labels, "Buttons" },
  { menu_item_home_jvs_view, "1P View" },
  { menu_item_hotkey_hold_time, "Hotkey Hold" },
  { menu_item_menu_hotkey, "Quick Menu" },
  { menu_item_system_menu_hotkey, "System Menu" },
  { menu_item_home_hotkey, "Home" },
  { menu_item_capture_hotkey, "Capture" },
  { menu_item_kiosk_mode, "Kiosk" },
  { menu_item_hotkeys, "Hotkey" },
  { menu_item_stick_invert, "Stick Invert" },
  { menu_item_rumble, "Rumble" },
  { menu_item_trigger_mode, "Triggers" },
  { menu_item_switch_rtrig_stick, "RTrig=RStick" },
  { menu_item_buzzer, "Sound" },
  { menu_item_latency_test, "Latency" },
  { menu_item_latency_controller, "Lat Ctrl" },
  { menu_item_latency_host, "Lat Host" },
  { menu_item_latency_run, "Lat Run" },
  { menu_item_button_remap, "Button Remap" },
  { menu_item_button_map, "Button Map" },
  { menu_item_n64_z_mode, "Z Button" },
  { menu_item_n64_cstick_mode, "N64 C Buttons" },
  { menu_item_wii_analog_range, "Stick Range" },
  { menu_item_n64_analog_range, "Stick Range" },
  { menu_item_mapping_view, "View Mapping" },
  //{ menu_item_pad_test, "Pad Test" },  // Removed - main display already shows real-time button visualization
  //{ menu_item_pin_debug, "Pin Debug" },  // Hidden - developer tool only
  { menu_item_screensaver, "Screensaver" },
  { menu_item_games, "Games" },
  { menu_item_guncon_offset, "GunCon Align" },
  { menu_item_powerpad, "Power Pad" },
  { menu_item_jogcon_mode, "JogCon Mode" },
  { menu_item_jogcon_force, "JogCon Force" },
  { menu_item_wheel_sensitivity, "Wheel Sens" },
  { menu_item_jogcon_digital, "Dig Output" },
  { menu_item_jogcon_wheel_axis, "Wheel Axis" },
  { menu_item_bluetooth_pairing, "BT Pair" },
  { menu_item_bluetooth_forget, "Forget BT" },
  { menu_item_factory_reset, "Factory Reset" },
  { menu_item_bootloader, "Bootloader" },
  { menu_item_about, "About" },
};

const uint8_t MENU_TOTAL_ITEMS = sizeof(menu_items) / sizeof(menu_line_t);
const uint8_t MENU_ITEM_ROWS = 6;  // Rows 1-6 for items, row 7 for Cancel/Save
