#pragma once

#include <stdint.h>

enum menu_item_enum : uint8_t {
  menu_item_exit = 0,
  menu_item_save_and_reboot,
  menu_item_reserved_internal,
  menu_item_input_mode,
  menu_item_output_mode,
  menu_item_analog_deadzone,
  menu_item_dpad_as_buttons,
  menu_item_socd,
  menu_item_nso_special,
  menu_item_display_contrast,
  menu_item_home_screen,
  menu_item_home_button_labels,
  menu_item_home_jvs_view,
  menu_item_hotkey_hold_time,
  menu_item_stick_invert,
  menu_item_rumble,
  menu_item_trigger_mode,
  menu_item_switch_rtrig_stick,
  menu_item_buzzer,
  menu_item_latency_test,
  menu_item_latency_controller,
  menu_item_latency_host,
  menu_item_latency_run,
  menu_item_button_remap,
  menu_item_factory_reset,
  menu_item_pad_test,
  menu_item_pin_debug,
  menu_item_screensaver,
  menu_item_games,
  menu_item_guncon_offset,
  menu_item_powerpad,
  menu_item_jogcon_mode,
  menu_item_jogcon_force,
  menu_item_wheel_sensitivity,
  menu_item_jogcon_digital,
  menu_item_jogcon_wheel_axis,
  menu_item_autodetect,
  menu_item_analog_test,
  menu_item_mapping_view,
  menu_item_button_map,
  menu_item_n64_z_mode,
  menu_item_n64_cstick_mode,
  menu_item_wii_analog_range,
  menu_item_n64_analog_range,
  menu_item_menu_hotkey,
  menu_item_system_menu_hotkey,
  menu_item_home_hotkey,
  menu_item_capture_hotkey,
  menu_item_kiosk_mode,
  menu_item_hotkeys,
  menu_item_bluetooth_pairing,
  menu_item_bluetooth_forget,
  menu_item_win_output,
  menu_item_psx_periph,
  menu_item_bootloader,
  menu_item_about,
};

typedef struct {
  menu_item_enum item;
  const char* text;
} menu_line_t;
