#pragma once

#include "../product_config.h"

#include "menu_pad_layouts.h"

namespace menu_pad_layouts_internal {

#define DECLARE_PAD_LAYOUT(layout_name, count_name) \
  extern const PadButton layout_name[]; \
  extern const uint8_t count_name;

DECLARE_PAD_LAYOUT(padLayoutWii, PAD_LAYOUT_WII_COUNT)
DECLARE_PAD_LAYOUT(padLayoutUsbModern, PAD_LAYOUT_USB_MODERN_COUNT)
DECLARE_PAD_LAYOUT(padLayoutUsbSwitch, PAD_LAYOUT_USB_SWITCH_COUNT)
DECLARE_PAD_LAYOUT(padLayoutSnes, PAD_LAYOUT_SNES_COUNT)
#ifdef ENABLE_INPUT_VBOY
DECLARE_PAD_LAYOUT(padLayoutVBoy, PAD_LAYOUT_VBOY_COUNT)
#endif
DECLARE_PAD_LAYOUT(padLayoutN64, PAD_LAYOUT_N64_COUNT)
DECLARE_PAD_LAYOUT(padLayoutGC, PAD_LAYOUT_GC_COUNT)
#ifdef ENABLE_INPUT_DREAMCAST
DECLARE_PAD_LAYOUT(padLayoutDreamcast, PAD_LAYOUT_DREAMCAST_COUNT)
DECLARE_PAD_LAYOUT(padLayoutDreamcastWheel, PAD_LAYOUT_DREAMCAST_WHEEL_COUNT)
#endif
DECLARE_PAD_LAYOUT(padLayoutPSXDigital, PAD_LAYOUT_PSX_DIGITAL_COUNT)
DECLARE_PAD_LAYOUT(padLayoutPopn, PAD_LAYOUT_POPN_COUNT)
DECLARE_PAD_LAYOUT(padLayoutGuitarFreaks, PAD_LAYOUT_GUITARFREAKS_COUNT)
DECLARE_PAD_LAYOUT(padLayoutDancePad, PAD_LAYOUT_DANCEPAD_COUNT)
DECLARE_PAD_LAYOUT(padLayoutVirtualJvs, PAD_LAYOUT_VIRTUAL_JVS_COUNT)
DECLARE_PAD_LAYOUT(padLayoutJvs6, PAD_LAYOUT_JVS6_COUNT)
DECLARE_PAD_LAYOUT(padLayoutJvs7, PAD_LAYOUT_JVS7_COUNT)
DECLARE_PAD_LAYOUT(padLayoutJvs8, PAD_LAYOUT_JVS8_COUNT)
DECLARE_PAD_LAYOUT(padLayoutPSX, PAD_LAYOUT_PSX_COUNT)
DECLARE_PAD_LAYOUT(padLayoutPSXDualShock, PAD_LAYOUT_PSX_DUALSHOCK_COUNT)
DECLARE_PAD_LAYOUT(padLayoutPS3, PAD_LAYOUT_PS3_COUNT)
#ifdef ENABLE_INPUT_JVS
DECLARE_PAD_LAYOUT(padLayoutJvs, PAD_LAYOUT_JVS_COUNT)
#endif
DECLARE_PAD_LAYOUT(padLayoutSaturn, PAD_LAYOUT_SATURN_COUNT)
DECLARE_PAD_LAYOUT(padLayoutSaturn3D, PAD_LAYOUT_SATURN3D_COUNT)
#ifdef ENABLE_INPUT_MEGADRIVE
DECLARE_PAD_LAYOUT(padLayoutGenesis6, PAD_LAYOUT_GENESIS6_COUNT)
DECLARE_PAD_LAYOUT(padLayoutGenesis3, PAD_LAYOUT_GENESIS3_COUNT)
#endif
DECLARE_PAD_LAYOUT(padLayoutNES, PAD_LAYOUT_NES_COUNT)
DECLARE_PAD_LAYOUT(padLayoutPowerPad, PAD_LAYOUT_POWERPAD_COUNT)
DECLARE_PAD_LAYOUT(padLayoutGeneric, PAD_LAYOUT_GENERIC_COUNT)
#ifdef ENABLE_INPUT_SMS
DECLARE_PAD_LAYOUT(padLayoutSMS, PAD_LAYOUT_SMS_COUNT)
#endif
#ifdef ENABLE_INPUT_JPC
DECLARE_PAD_LAYOUT(padLayoutJPC, PAD_LAYOUT_JPC_COUNT)
#endif
#ifdef ENABLE_INPUT_PCE
DECLARE_PAD_LAYOUT(padLayoutPCE, PAD_LAYOUT_PCE_COUNT)
DECLARE_PAD_LAYOUT(padLayoutPCE2, PAD_LAYOUT_PCE2_COUNT)
#endif
#ifdef ENABLE_INPUT_NEOGEO
DECLARE_PAD_LAYOUT(padLayoutNeoGeo, PAD_LAYOUT_NEOGEO_COUNT)
#endif
#ifdef ENABLE_INPUT_3DO
DECLARE_PAD_LAYOUT(padLayout3DO, PAD_LAYOUT_3DO_COUNT)
#endif
#ifdef ENABLE_INPUT_JAGUAR
DECLARE_PAD_LAYOUT(padLayoutJaguar, PAD_LAYOUT_JAGUAR_COUNT)
DECLARE_PAD_LAYOUT(padLayoutJaguarRotary, PAD_LAYOUT_JAGUAR_ROTARY_COUNT)
#endif
#ifdef ENABLE_INPUT_INTV
DECLARE_PAD_LAYOUT(padLayoutIntv, PAD_LAYOUT_INTV_COUNT)
#endif
#ifdef ENABLE_INPUT_DRIVING
DECLARE_PAD_LAYOUT(padLayoutDriving, PAD_LAYOUT_DRIVING_COUNT)
#endif

#undef DECLARE_PAD_LAYOUT

}  // namespace menu_pad_layouts_internal
