#pragma once

#define FIRMWARE_VERSION_MAJOR 1
#define FIRMWARE_VERSION_MINOR 0
#define FIRMWARE_VERSION_PATCH 0
#define FIRMWARE_VERSION_STRING "1.0.0"
#define FIRMWARE_VERSION_TAG "v" FIRMWARE_VERSION_STRING
#define FIRMWARE_BUILD_DATE __DATE__
#define FIRMWARE_BUILD_TIME __TIME__
#define FIRMWARE_HARDWARE_STRING "RP2040 2MB"
